import math

import numpy as np
import pytest

from src.chi_bio_candidate_math import spectral_radius
from src.chi_bio_g2_qualification import (
    exact_shared_transition_exists,
    g2_entrywise_noise_pilot,
    g2_interval_disposition,
    largest_singular_value,
    sampling_interval_consistency,
)


def test_g2_unit_circle_known_truth_cases():
    assert spectral_radius(np.diag([0.4, 0.9])) == pytest.approx(0.9)
    assert spectral_radius(np.diag([0.4, 1.0])) == pytest.approx(1.0)
    assert spectral_radius(np.diag([0.4, 1.1])) == pytest.approx(1.1)


def test_sampling_interval_reference_conversion_is_consistent_for_semigroup_truth():
    alpha = -0.2
    intervals = (0.5, 1.0, 2.0)
    radii = tuple(math.exp(alpha * d) for d in intervals)
    values = sampling_interval_consistency(radii, intervals, reference_interval=1.0)
    assert values == pytest.approx((math.exp(alpha),) * 3)


def test_sampling_interval_inconsistency_refuses_single_rate_interpretation():
    with pytest.raises(ValueError, match="inconsistent"):
        sampling_interval_consistency((0.9, 0.9), (1.0, 2.0), reference_interval=1.0)


def test_nonnormal_transition_keeps_transient_warning_visible():
    t = np.array([[0.8, 4.0], [0.0, 0.8]])
    assert spectral_radius(t) == pytest.approx(0.8)
    assert largest_singular_value(t) > 1.0


def test_time_varying_transitions_can_refuse_one_shared_operator():
    # Two-dimensional states generated by incompatible one-step maps.
    x_now = np.array([[1.0, 0.0], [0.0, 1.0], [1.0, 1.0]])
    x_next_consistent = np.array([[0.8, 0.0], [0.0, 0.9], [0.8, 0.9]])
    x_next_inconsistent = np.array([[0.8, 0.0], [0.0, 0.9], [1.4, 0.2]])

    assert exact_shared_transition_exists(x_now, x_next_consistent)
    assert not exact_shared_transition_exists(x_now, x_next_inconsistent)


def test_g2_noise_pilot_is_deterministic_and_can_span_unity():
    truth = np.diag([0.5, 0.8, 0.98])
    a = g2_entrywise_noise_pilot(truth, sigma=0.02, replicates=200, seed=20260912)
    b = g2_entrywise_noise_pilot(truth, sigma=0.02, replicates=200, seed=20260912)
    assert a == b
    assert a.truth_value == pytest.approx(0.98)
    assert a.truth_covered is True
    assert a.unity_disposition in {"BELOW_UNITY_RESOLVED", "UNCERTAINTY_SPANS_BOUNDARY"}


def test_g2_interval_disposition_refuses_boundary_spanning_uncertainty():
    assert g2_interval_disposition(np.array([0.9, 0.95, 0.98])) == "BELOW_UNITY_RESOLVED"
    assert g2_interval_disposition(np.array([1.02, 1.05, 1.1])) == "ABOVE_UNITY_RESOLVED"
    assert g2_interval_disposition(np.array([0.95, 1.0, 1.05])) == "UNCERTAINTY_SPANS_BOUNDARY"
