import numpy as np
import pytest

from nsd_engine.ar2_modal import AR2Truth, fit_ar2_modal, simulate_ar2_truth
from nsd_engine.schema import RefusalCode


@pytest.mark.parametrize(
    "frequency_hz,zeta",
    [
        (5.0, 0.2),
        (10.0, 0.5),
        (20.0, 0.8),
    ],
)
def test_ar2_known_truth_recovers_frequency_and_damping(frequency_hz, zeta):
    truth = AR2Truth(
        natural_frequency_hz=frequency_hz,
        damping_ratio=zeta,
        sampling_rate_hz=256.0,
    )
    signal = simulate_ar2_truth(
        truth,
        seconds=120.0,
        innovation_sd=1.0,
        measurement_noise_sd=0.0,
        seed=20260914,
    )
    result = fit_ar2_modal(signal, truth.sampling_rate_hz)

    assert result.admitted is True
    assert result.refusal_code is None
    assert result.natural_frequency_hz == pytest.approx(frequency_hz, rel=0.04)
    assert result.damping_ratio == pytest.approx(zeta, abs=0.04)
    assert result.damped_frequency_hz == pytest.approx(truth.damped_frequency_hz, rel=0.05)
    assert result.decay_rate_per_s == pytest.approx(truth.decay_rate_per_s, rel=0.08)


def test_ar2_recovers_discrete_coefficients_on_long_truth():
    truth = AR2Truth(12.0, 0.4, 256.0)
    signal = simulate_ar2_truth(truth, seconds=180.0, seed=11)
    result = fit_ar2_modal(signal, truth.sampling_rate_hz)
    expected_a1, expected_a2 = truth.ar_coefficients

    assert result.admitted is True
    assert result.a1 == pytest.approx(expected_a1, abs=0.015)
    assert result.a2 == pytest.approx(expected_a2, abs=0.015)


def test_ar2_refuses_too_short_signal():
    result = fit_ar2_modal(np.ones(100), 256.0, min_samples=256)
    assert result.admitted is False
    assert result.refusal_code is RefusalCode.SIGNAL_INSUFFICIENT


def test_ar2_refuses_nonfinite_signal():
    signal = np.ones(300)
    signal[20] = np.nan
    result = fit_ar2_modal(signal, 256.0)
    assert result.admitted is False
    assert result.refusal_code is RefusalCode.SIGNAL_INSUFFICIENT


def test_ar2_refuses_zero_variance():
    result = fit_ar2_modal(np.ones(512), 256.0)
    assert result.admitted is False
    assert result.refusal_code is RefusalCode.MODE_NONIDENTIFIABLE


def test_ar2_refuses_stable_real_poles_as_nonoscillatory():
    # x[t] generated by two stable real exponentials has no complex modal pair.
    n = 2000
    t = np.arange(n, dtype=float)
    signal = 0.9**t + 0.5 * 0.7**t
    result = fit_ar2_modal(signal, 100.0, min_samples=100)
    assert result.admitted is False
    assert result.refusal_code is RefusalCode.MODE_NONIDENTIFIABLE


def test_ar2_measurement_noise_bias_is_not_silently_called_exact():
    truth = AR2Truth(10.0, 0.5, 256.0)
    clean = simulate_ar2_truth(truth, seconds=120.0, seed=12, measurement_noise_sd=0.0)
    noisy = simulate_ar2_truth(truth, seconds=120.0, seed=12, measurement_noise_sd=4.0)
    clean_fit = fit_ar2_modal(clean, 256.0)
    noisy_fit = fit_ar2_modal(noisy, 256.0)

    assert clean_fit.admitted is True
    # The current estimator may admit the noisy series mechanically, but the
    # known-truth test explicitly demonstrates that measurement noise can move
    # the inferred pole and therefore requires a future operating-region map.
    if noisy_fit.admitted:
        clean_error = abs(clean_fit.damping_ratio - truth.damping_ratio)
        noisy_error = abs(noisy_fit.damping_ratio - truth.damping_ratio)
        assert noisy_error >= clean_error
